### ISSUE TITLE
N support stream api?

### ISSUE THREAD

**Issue by hotchemi** [yaraki/slides#1]
@yaraki 

http://yaraki.github.io/slides/gds-2016q2/index.html

In this slide, you said there is no plan to support Stream API, but it seems there is already stream implementation in AOSP.

https://android.googlesource.com/platform/libcore/+/master/ojluni/src/main/java/java/util/stream/

**Comment by yaraki** [comment]
後方互換じゃない (N でしか動かない) という話です

**Comment by hotchemi** [comment]
OK, Sorry!
